### ISSUE TITLE
好像会和hexo-douban起冲突

### ISSUE THREAD

**Issue by glennw97** [hqweay/hexo-douban-getter#1]

**Comment by hqweay** [comment]
两个插件在 hexo 中注册的名称都是 douban，所以冲突了...

![image](https://user-images.githubusercontent.com/23608642/78693514-f179c500-792d-11ea-9d04-50c8a9be717f.png)

你可以进 `node_modules/hexo-douban-getter/index.js` 修改上图的 douban 为其它任意不冲突的名字，比如 `douabn-test`，然后使用的时候，用：

```
{% douban-test "hqweay" "watchedMovies" 1 3 h3 %}
```
这样即可。

**Comment by Shen-LiPing** [comment]
感谢，该问题已解决！

**Comment by Shen-LiPing** [comment]
IOS以及PC端的IE浏览器无法加载图片。在head.ejs的<head></head>标签内加入<meta name="referrer" content="no-referrer"> 可以解决但会和不蒜子统计插件起冲突导致其无法显示统计到的访客数据不知是否有别的解决方案？

**Comment by hqweay** [comment]
> IOS以及PC端的IE浏览器无法加载图片。在head.ejs的标签内加入 可以解决但会和不蒜子统计插件起冲突导致其无法显示统计到的访客数据不知是否有别的解决方案？

你是在 head.ejs 加入什么解决的？是 no-refer 的 meta 标签吗？如果是这个问题，你可以尝试修改 
`/src/listRender/itemTemplateRender.js` 里的 img 标签。

直接在 head.ejs 添加会覆盖全局 http 请求，可能会与统计冲突。修改代码中的 img 标签，就只会影响豆瓣数据的图片。

如果是其它问题，还烦请具体描述下。我没有相应环境，不好复现问题。

**Comment by glennw97** [comment]
![](https://i.loli.net/2020/04/13/dov4MQNfDlH3e1s.jpg)
![](https://i.loli.net/2020/04/13/SAXqZWELUn7YrH1.jpg)
我是这样改的还是在手机端打不开图片。目前PC端的Chrome能打开图片，PC端的Edge和手机端的safari以及微信内置浏览器均打不开图片。

**Comment by hqweay** [comment]
要为 img 标签单独设置 refferer，似乎只能用 referrerpolicy="no-referrer"。

而部分浏览器并不支持  referrerpolicy ……

![image](https://user-images.githubusercontent.com/23608642/79134955-2def6a00-7de1-11ea-9e7e-07f772556b79.png)


至于微信浏览器，我用安卓的微信访问没问题。我记得 IOS 端的浏览器似乎都是用的苹果的内核，所以产生了这个问题……？（我不确定）

不好意思，这个问题我暂时解决不了。😂😂

如果你解决了，请一定传授一下我。😂

我有一个思路，可以在 meta 标签设置 referrer 为 always，然后在会用到豆瓣的图片的页面通过 JavaScript 设置 refferer 为 no-referrer……这样就只需要牺牲需要用到豆瓣的图片的页面的统计。

PS：我做个判断，当使用 IE 或者 Safari，隐藏图片好了...

**Comment by hqweay** [comment]
> ![](https://camo.githubusercontent.com/c9e70b5e46a064b1ba535e95b24290a988560004/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f31332f646f76344d514e66446c48336531732e6a7067)
> ![](https://camo.githubusercontent.com/db39dcae72cbad4b9ac76c04b3c1d5c913175813/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f31332f534158715a57454c556e37597248312e6a7067)
> 我是这样改的还是在手机端打不开图片。目前PC端的Chrome能打开图片，PC端的Edge和手机端的safari以及微信内置浏览器均打不开图片。

更新了，现在图片加载失败后会成功隐藏起来。

**Comment by glennw97** [comment]
PC端的IE目前能实现图片隐藏效果，IOS端的safari能实现图片访问，Chrome能实现图片隐藏 。但是微信内置浏览器还是会出现图片加载失败情况。

![](https://i.loli.net/2020/04/15/eLM7YFEQHdG4Ra8.jpg)
![](https://i.loli.net/2020/04/15/BdeI1cL7839UNv4.jpg)
![](https://i.loli.net/2020/04/15/lsAr9Tq8Huy4bPd.jpg)
![](https://i.loli.net/2020/04/15/sT5fPpqkw9aFVj6.jpg)

**Comment by hqweay** [comment]
> PC端的IE目前能实现图片隐藏效果，IOS端的safari能实现图片访问，Chrome能实现图片隐藏 。但是微信内置浏览器还是会出现图片加载失败情况。
> 
> ![](https://camo.githubusercontent.com/d6e8055dece95c226b6567d2738097e257a6bdb1/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f31352f654c4d3759464551486447345261382e6a7067)
> ![](https://camo.githubusercontent.com/2bbbaa0e5d6fdc6d03124cd38bb8131e11282797/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f31352f4264654931634c37383339554e76342e6a7067)
> ![](https://camo.githubusercontent.com/90cd2538c41e85492e7e86c1dfc258bcdc46a139/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f31352f6c73417239547138487579346250642e6a7067)
> ![](https://camo.githubusercontent.com/39cebf09ee7df7bff9509d3042e5df2a56157687/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f31352f735435665070716b77396146566a362e6a7067)

理论上获取图片失败是会隐藏的。问题要么是获取成功了但是没显示，要么是 js 没执行。

我认为后者可能性大些，你可以在尝试刷新一下页面，看看图片是否会隐藏。

因为插件的限制，js 代码放置的位置在一些情况下会加载失败。

如果还不行的话，那可能是浏览器内核差异的关系了……这样的话，非常抱歉，我暂时没能力解决。😅😅
