### ISSUE TITLE
请问可以修改样式吗？

### ISSUE THREAD

**Issue by W4J1e** [hqweay/hexo-douban-getter#4]
比如添加下划线、标题居中之类的……如果作者没时间的话我可以尝试自己修改吗？

**Comment by hqweay** [comment]
> 比如添加下划线、标题居中之类的……如果作者没时间的话我可以尝试自己修改吗？

没问题哈，随便修改玩，欢迎提 pr。作者当社畜了...😅😅我找时间（尽量这周末）维护下。

**Comment by W4J1e** [comment]
> > 比如添加下划线、标题居中之类的……如果作者没时间的话我可以尝试自己修改吗？
> 
> 没问题哈，随便修改玩，欢迎提 pr。作者当社畜了...😅😅我找时间（尽量这周末）维护下。

同为社畜，也没啥能力，就瞎折腾一下😂现在还在开会，在偷偷看代码

**Comment by hqweay** [comment]
> > > 比如添加下划线、标题居中之类的……如果作者没时间的话我可以尝试自己修改吗？
> > 
> > 
> > 没问题哈，随便修改玩，欢迎提 pr。作者当社畜了...😅😅我找时间（尽量这周末）维护下。
> 
> 同为社畜，也没啥能力，就瞎折腾一下😂现在还在开会，在偷偷看代码

哈哈哈哈，太真实了。我那阵子也在划水（逃
