### ISSUE TITLE
建议电影页面展示也能有书本状态切换按钮

### ISSUE THREAD

**Issue by webyang-male** [hqweay/hexo-douban-getter#6]
如题

**Comment by hqweay** [comment]
> 如题

现在是可以的 - - 刚加了个例子你阔以瞧瞧 [https://leay.net/2020/04/13/hexo-douban-getter/](https://leay.net/2020/04/13/hexo-douban-getter/)

**Comment by hqweay** [comment]
不过如果把电影和书籍放到一个页面时，切换似乎会有问题。【电影和书籍用的同样的id，切换时无法分辨。】- -

**Comment by webyang-male** [comment]
> 不过如果把电影和书籍放到一个页面时，切换似乎会有问题。【电影和书籍用的同样的id，切换时无法分辨。】- -

感谢作者大大细心回复,thx,原先没咋看懂教程语法
